version: '3.8'

services:
  app:
    image: auth_app
    build:
      context: .
    container_name: auth_app
    ports:
      - '4000:${PORT}'
    env_file:
      - .env
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  db_data:
