version: '3.8'

services:
  database:
    image: postgres:17.6
    container_name: poll_database
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - '${DB_PORT}:5432'
    restart: always
    tty: true

  app:
    image: auth_app
    container_name: auth_app
    ports:
      - '4000:4000'
    env_file:
      - .env
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  db_data:
